force-app/main/default/objects/Purchase_Invoice__c/Purchase_Invoice__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice</label>
    <nameField>
        <displayFormat>PINV{00000}</displayFormat>
        <label>Purchase Invoice Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Purchase Invoices</relationshipLabel>
    <relationshipName>Purchase_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Invoice__c/fields/Total_Amount_to_Pay__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_to_Pay__c</fullName>
    <label>Total Amount to Pay</label>
    <summarizedField>Purchase_Invoice_Item__c.Total_Price__c</summarizedField>
    <summaryForeignKey>Purchase_Invoice_Item__c.Purchase_Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/UtilClass.cls
public class UtilClass {
	
    public static void UpdateContactViaPurchaseInvoice(Set<Id> customerIdSet){
        //When we have to perform sum, min, max or Count then we have to perform a special type of SOQL
        //Query called as aggregate query.
        List<AggregateResult> aggregateResultList = new List<AggregateResult>();
        aggregateResultList = [
            SELECT SUM(Total_Amount_to_Pay__c) totalPay, Customer__c
            FROM Purchase_Invoice__c
            WHERE Customer__c IN :customerIdSet
            GROUP BY Customer__c
        ];
        
        List<Contact> contactList = new List<Contact>();
        for(AggregateResult agrObj :aggregateResultList){
            Contact contactObj = new Contact();
            contactObj.Id = ''+agrObj.get('Customer__c');
            contactObj.Total_Purchase_Amount__c = Decimal.valueOf(''+agrObj.get('totalPay'));
            contactList.add(contactObj);
        }
        
        if(contactList.size() > 0){
            UPDATE contactList;
        }
    }
}