force-app/main/default/objects/Purchase_Invoice__c/Purchase_Invoice__c.object-meta.xml
<CustomObject>
    <label>Purchase Invoice</label>
    <nameField>
        <displayFormat>PINV{00000}</displayFormat>
        <label>Purchase Invoice Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Invoices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Purchase Invoices</relationshipLabel>
    <relationshipName>Purchase_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Invoice__c/fields/Total_Amount_to_Pay__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_to_Pay__c</fullName>
    <label>Total Amount to Pay</label>
    <summarizedField>Purchase_Invoice_Item__c.Total_Price__c</summarizedField>
    <summaryForeignKey>Purchase_Invoice_Item__c.Purchase_Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/PurchaseInvoiceTriggerHelper.cls
public class PurchaseInvoiceTriggerHelper {
	
    public Static void afterUpdate(List<Purchase_Invoice__c> newPurchaseInvList, Map<id, Purchase_Invoice__c> oldPurchaseInvByIdMap){
        
        Set<Id> customerIdSet = new Set<Id>();
        for(Purchase_Invoice__c newPurchaseInvObj :newPurchaseInvList){
            Purchase_Invoice__c oldPurchaseInvObj = oldPurchaseInvByIdMap.get(newPurchaseInvObj.Id);
            //Check the amount is changed.
            if(newPurchaseInvObj.Total_Amount_to_Pay__c != oldPurchaseInvObj.Total_Amount_to_Pay__c){
                //Capture all Ids, because we can't do Update in LOOP.
                customerIdSet.add(newPurchaseInvObj.Customer__c);
            }
        }
        
        if(customerIdSet.size() > 0){
            UtilClass.UpdateContactViaPurchaseInvoice(customerIdSet);
        }
    }

	
    public Static void afterDelete(List<Purchase_Invoice__c> oldPurchaseInvList){
        
        Set<Id> customerIdSet = new Set<Id>();
        for(Purchase_Invoice__c newPurchaseInvObj :oldPurchaseInvList){
            customerIdSet.add(newPurchaseInvObj.Customer__c);
        }
        if(customerIdSet.size() > 0){
            UtilClass.UpdateContactViaPurchaseInvoice(customerIdSet);
        }
    }
}