force-app/main/default/objects/Furniture__c/Furniture__c.object-meta.xml
<CustomObject>
    <label>Furniture</label>
    <nameField>
        <label>Furniture Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Furnitures</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Furniture__c/fields/Materials__c.field-meta.xml
<CustomField>
    <fullName>Materials__c</fullName>
    <label>Materials</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Metal</fullName>
            </value>
            <value>
                <fullName>Plastic</fullName>
            </value>
            <value>
                <fullName>Steel</fullName>
            </value>
            <value>
                <fullName>Wood</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Furniture__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Why we are Creating this field?</description>
    <inlineHelpText>Why do you have to fill in detail?</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Beds</fullName>
            </value>
            <value>
                <fullName>Chairs</fullName>
            </value>
            <value>
                <fullName>Dressers</fullName>
            </value>
            <value>
                <fullName>Nightstand</fullName>
            </value>
            <value>
                <fullName>Sofas</fullName>
            </value>
            <value>
                <fullName>Tables</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SUM23Day4.cls
public class SUM23Day4 {
    //sObject in Apex.
    /*
     * 
     * "sObject obj" ===> "datatype variableName".
     * 	sObject obj = new sObject(); '= new', means that we are allocating memory to the variable. 
		obj.fieldName = value;, 'Using the DOT operator we are accessing the FieldName'.

		We are Using sObject in Apex to perform DML(INSERT, UPDATE, and DELETE).
     * */
    public SUM23Day4(){
        /*
        Lead ldObj = new Lead();
        ldObj.FirstName = 'Suraj';
        ldObj.LastName = 'Test';
        ldObj.Email = 'test@code.com';
        ldObj.Company = 'apex';
        //...
        INSERT ldObj;
		*/
        
        Furniture__c furnitureObj = new Furniture__c();
        furnitureObj.Name = '4 X 4 Desk';
        furnitureObj.Type__c = 'Chairs';
        furnitureObj.Price__c = 234.98;
        furnitureObj.Size__c = '60 X 60 X 29';
        furnitureObj.Materials__c = 'Metal'; 
        //...
        INSERT furnitureObj;
    }
}